"""initial_migration

Revision ID: 3c885b504dad
Revises: 
Create Date: 2025-11-05 21:16:01.480998+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c885b504dad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(length=100), nullable=False),
    sa.Column('current_state', sa.Enum('START', 'EMOTION_CHECK', 'CRISIS_INTERVENTION', 'HIGH_DISTRESS', 'MODERATE_SUPPORT', 'CASUAL_CHAT', 'LETTER_WRITING', 'GOAL_TRACKING', 'TECHNIQUE_SELECTION', 'TECHNIQUE_EXECUTION', 'END_SESSION', name='conversationstateenum'), nullable=True),
    sa.Column('therapy_phase', sa.Enum('CRISIS', 'UNDERSTANDING', 'ACTION', 'SUSTAINABILITY', name='therapyphaseenum'), nullable=True),
    sa.Column('emotional_score', sa.Float(), nullable=True),
    sa.Column('crisis_level', sa.Float(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('crisis_incidents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=True),
    sa.Column('data_retention_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('specific', sa.Text(), nullable=True),
    sa.Column('measurable', sa.Text(), nullable=True),
    sa.Column('achievable', sa.Text(), nullable=True),
    sa.Column('relevant', sa.Text(), nullable=True),
    sa.Column('time_bound', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('milestones', sa.JSON(), nullable=True),
    sa.Column('completed_milestones', sa.JSON(), nullable=True),
    sa.Column('blockers', sa.JSON(), nullable=True),
    sa.Column('blocker_resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('recipient_role', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('draft_content', sa.Text(), nullable=True),
    sa.Column('communication_style', sa.String(length=50), nullable=True),
    sa.Column('tone_assessment', sa.JSON(), nullable=True),
    sa.Column('guardrail_checks', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('revision_history', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('emotions_processed', sa.JSON(), nullable=True),
    sa.Column('initial_emotional_state', sa.String(length=50), nullable=True),
    sa.Column('final_emotional_state', sa.String(length=50), nullable=True),
    sa.Column('is_time_capsule', sa.Boolean(), nullable=True),
    sa.Column('time_capsule_open_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('initial_emotional_score', sa.Float(), nullable=True),
    sa.Column('final_emotional_score', sa.Float(), nullable=True),
    sa.Column('primary_emotion', sa.String(length=50), nullable=True),
    sa.Column('techniques_used', sa.JSON(), nullable=True),
    sa.Column('topics_discussed', sa.JSON(), nullable=True),
    sa.Column('session_quality', sa.Float(), nullable=True),
    sa.Column('therapeutic_alliance', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('therapist_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('detected_emotions', sa.JSON(), nullable=True),
    sa.Column('emotional_intensity', sa.Float(), nullable=True),
    sa.Column('distress_level', sa.String(length=20), nullable=True),
    sa.Column('crisis_detected', sa.Boolean(), nullable=True),
    sa.Column('crisis_confidence', sa.Float(), nullable=True),
    sa.Column('guardrail_triggered', sa.String(length=100), nullable=True),
    sa.Column('conversation_state', sa.String(length=50), nullable=True),
    sa.Column('technique_context', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('sessions')
    op.drop_table('letters')
    op.drop_table('goals')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
